import Head from "next/head";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { db, auth } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };
  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div className=" m-4">
      <Head>
        <title>Thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-6 px-2 text-lg font-medium text-center  ">
        <h2> Feed </h2>
        <div className="text-left flex flex-wrap">
          {allPosts.map((post) => (
            <div className=" w-full  sm:w-1/2 md:w-1/2 lg:w-1/3 xl:w-1/3 bg-slate-100 mb-4 p-8 rounded overflow-hidden shadow-lg hover:scale-110 transition duration-300 ease-in-out">

             <Message {...post} key={post.id} >
              <Link href={{pathname:`/${post.id}` , query:{...post}}}>
                <button>{post.comments?.length > 0 ? post.comments?.length: 0 } Comments </button>
              </Link>
            </Message>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
